version: "3.8"

services:
  sotypot-landing:
    build: .
    ports:
      - "8888:80"    # HTTP (redirige a HTTPS)
      - "8887:443"   # HTTPS seguro con auth básica
    container_name: sotypot-landing
    restart: unless-stopped
